# status: https://travis-ci.org/nicolasdespres/pyloc
# documentation: http://docs.travis-ci.com/user/languages/python/
language: python
python:
    - 3.4
    - 3.3
    - 3.2
    - 2.7
sudo: false
script: nosetests
