# status: https://travis-ci.org/nicolasdespres/pyloc
# documentation: http://docs.travis-ci.com/user/languages/python/
language: python
python:
    - 3.5
    - 3.4
    - 3.3
    - 2.7
sudo: false
install:
    - pip install coveralls coverage
script:
    - coverage erase
    - echo 'import coverage; coverage.process_startup()' > sitecustomize.py
    - export COVERAGE_PROCESS_START=.coveragerc
    - coverage run setup.py test;
    - rm -f sitecustomize.py sitecustomize.pyc
after_success:
    - coverage combine
    - coverage report
    - coveralls --verbose
