# status: https://travis-ci.org/nicolasdespres/pyloc
# documentation: http://docs.travis-ci.com/user/languages/python/
language: python
python:
    - 3.5
    - 3.4
    - 3.3
    - 3.2
    - 2.7
sudo: false
install:
    - pip install coveralls coverage
script:
    - PY_VERSION=$(python -c 'from sys import version_info as vi; print("%d%d"%(vi.major,vi.minor))')
    - if [ $PY_VERSION = 32 ]; then
        python -m unittest -v test_pyloc;
      else
        coverage run --source=pyloc.py setup.py test;
      fi
after_success:
    - coveralls
