#!/bin/bash
#
#::BEGIN::
# USAGE
#
#  etags
#
# DESCRIPTION
#
#  Make etags for the project.
#
# Copyright (c) 2016, Nicolas Despres
# Report any problem to <nicolas.despres@gmail.com>
#::END::
#

set -o errexit
set -o nounset

export LC_ALL=C
unset CDPATH

# Print its arguments on stderr prefixed by the base name of this script.
stderr()
{
  echo >&2 "`basename "$0"`: $@"
}

# Print its arguments on stderr prefixed by the base name of this script and
# a 'fatal' tag.
fatal()
{
  stderr "fatal: $@"
  exit 1
}

test $(git rev-parse --git-dir) = '.git' \
  || fatal "run me from the root directory of the project."

for FIND in gfind find
do
  type $FIND &>/dev/null && break
done

for XARGS in gxargs xargs
do
  type $XARGS &>/dev/null && break
done

rm -rf build .tox
$FIND . \
     -not -regex '^.*/\.git/.*$' \
     -type f \
     \( \( -name '*.py' \) -o \
     \( -perm '/a+x' -exec grep -q '^#!.*python' {} \; \) \) \
     -print0 \
  | $XARGS -0 etags -l python
